server:
  port: 8085

open-ai:
  bearer-key:

video-generation:
  output-path: /Users/vladislavabrosimov/IdeaProjects/VideoSkif/src/main/resources/output{num}.mp4

do:
  spaces:
    key: "EI6ML7AKJTFPJPUZGUZF"
    secret: "DNxgO67ZyMF+CLN2gsxGrugdygOUwCOXsNh8H0pJQWg"
    endpoint: "digitaloceanspaces.com"
    region: "fra1"
    bucket: "gunmarket.fra1"