### GET request with a header
GET http://localhost:8085/topic/Achamenid Persian Army
Accept: application/json

### Send POST request with json body
POST http://localhost:8085/image
Content-Type: application/json

{
  "src": "https://oaidalleapiprodscus.blob.core.windows.net/private/org-oymrFb2GrdFZbEK4snFqDPoG/user-XPJIyq8TpKMoKahb9vectKGs/img-y7X7bcLwqMIpgXsbyGBn7zX1.png?st=2023-04-21T13%3A00%3A31Z&se=2023-04-21T15%3A00%3A31Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-04-21T12%3A00%3A56Z&ske=2023-04-22T12%3A00%3A56Z&sks=b&skv=2021-08-06&sig=AWUkbz57ri%2BNCwflErXqCXhG6iJqRLZW6kyy5Ga4Ycg%3D"
}